// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA20KKWwoGdanuIokcQpqHPjc7eLriKuB0',
    appId: '1:934729990796:web:995a406e0e7c51749631a9',
    messagingSenderId: '934729990796',
    projectId: 'solex-72c53',
    authDomain: 'solex-72c53.firebaseapp.com',
    storageBucket: 'solex-72c53.appspot.com',
    measurementId: 'G-PKSSYTVHYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY2UqO1rvxrxZAS8SulwcQEq4jgyygDmk',
    appId: '1:934729990796:android:29ea0470e125e5b89631a9',
    messagingSenderId: '934729990796',
    projectId: 'solex-72c53',
    storageBucket: 'solex-72c53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNYQWLQpVfRTxOjsOx-Bc3Z3U-YWZT4gc',
    appId: '1:934729990796:ios:e76e2b3a30240d5e9631a9',
    messagingSenderId: '934729990796',
    projectId: 'solex-72c53',
    storageBucket: 'solex-72c53.appspot.com',
    iosBundleId: 'com.example.solex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNYQWLQpVfRTxOjsOx-Bc3Z3U-YWZT4gc',
    appId: '1:934729990796:ios:6bb87e9e7cdc2d499631a9',
    messagingSenderId: '934729990796',
    projectId: 'solex-72c53',
    storageBucket: 'solex-72c53.appspot.com',
    iosBundleId: 'com.example.solex.RunnerTests',
  );
}
